export const CONFIGURATION_TOKEN = Symbol('CONFIGURATION_TOKEN');
export const READINESS_PROBE_TOKEN = Symbol('READINESS_PROBE_TOKEN');

// MB-197: Resource BFF tokens
export const DATABASE_SERVICE_TOKEN = Symbol('DATABASE_SERVICE_TOKEN');
export const RESOURCE_REPOSITORY_TOKEN = Symbol('RESOURCE_REPOSITORY_TOKEN');
export const RESOURCE_SERVICE_TOKEN = Symbol('RESOURCE_SERVICE_TOKEN');
export const E2E_OUTAGE_STATE_TOKEN = Symbol('E2E_OUTAGE_STATE_TOKEN');
