package com.mentalbridge.care.support;

public enum DomainReasonCode {
	PHQ9_LEVEL_MINIMAL,
	PHQ9_LEVEL_MILD,
	PHQ9_LEVEL_MODERATE,
	PHQ9_LEVEL_MODERATELY_SEVERE,
	PHQ9_LEVEL_SEVERE,
	GAD7_LEVEL_MINIMAL,
	GAD7_LEVEL_MILD,
	GAD7_LEVEL_MODERATE,
	GAD7_LEVEL_SEVERE
}
