--liquibase formatted sql

--changeset mentalbridge:care-018-screening-meaning-copy
UPDATE screening_band_meaning
SET content_version = 'mb-screening-meaning-vi-vn-v2',
    meaning_text = CASE
        WHEN instrument = 'PHQ9' AND screening_level = 'MINIMAL' THEN 'Trong 14 ngày qua, các câu trả lời PHQ-9 của bạn cho thấy những dấu hiệu liên quan đến tâm trạng, hứng thú, giấc ngủ, năng lượng và sinh hoạt xuất hiện rất ít hoặc hầu như không xuất hiện. Kết quả này giúp bạn nhìn lại giai đoạn vừa qua, nhưng không có nghĩa là mọi khía cạnh cảm xúc của bạn đều đã được phản ánh đầy đủ.'
        WHEN instrument = 'PHQ9' AND screening_level = 'MILD' THEN 'Trong 14 ngày qua, các câu trả lời PHQ-9 của bạn cho thấy một số dấu hiệu liên quan đến tâm trạng, hứng thú, giấc ngủ, năng lượng hoặc sinh hoạt ở mức nhẹ. Bạn có thể dùng kết quả này để nhận ra điều gì đang làm mình khó chịu và theo dõi xem những dấu hiệu đó có kéo dài hoặc ảnh hưởng đến cuộc sống hằng ngày hay không.'
        WHEN instrument = 'PHQ9' AND screening_level = 'MODERATE' THEN 'Trong 14 ngày qua, các câu trả lời PHQ-9 của bạn cho thấy nhiều dấu hiệu liên quan đến tâm trạng, hứng thú, giấc ngủ, năng lượng hoặc sinh hoạt ở mức trung bình. Những trải nghiệm này có thể đáng để bạn quan tâm hơn, nhất là khi chúng kéo dài hoặc gây khó khăn trong học tập, công việc, các mối quan hệ hay việc chăm sóc bản thân.'
        WHEN instrument = 'PHQ9' AND screening_level = 'MODERATELY_SEVERE' THEN 'Trong 14 ngày qua, các câu trả lời PHQ-9 của bạn cho thấy nhiều dấu hiệu liên quan đến tâm trạng, hứng thú, giấc ngủ, năng lượng hoặc sinh hoạt ở mức khá nặng. Kết quả cho thấy bạn đang ghi nhận khó khăn ở nhiều nội dung của bài sàng lọc; chủ động tìm một người có chuyên môn để trao đổi có thể giúp bạn hiểu rõ hơn điều mình đang trải qua.'
        WHEN instrument = 'PHQ9' AND screening_level = 'SEVERE' THEN 'Trong 14 ngày qua, các câu trả lời PHQ-9 của bạn cho thấy nhiều dấu hiệu liên quan đến tâm trạng, hứng thú, giấc ngủ, năng lượng hoặc sinh hoạt ở mức nặng. Kết quả cho thấy các khó khăn được hỏi đến xuất hiện với tần suất cao; bạn nên cân nhắc sớm trao đổi trực tiếp với một chuyên gia phù hợp để được đánh giá đầy đủ hơn.'
        WHEN instrument = 'GAD7' AND screening_level = 'MINIMAL' THEN 'Trong 14 ngày qua, các câu trả lời GAD-7 của bạn cho thấy những dấu hiệu như lo lắng, căng thẳng hoặc khó thư giãn xuất hiện rất ít hoặc hầu như không xuất hiện. Kết quả này chỉ giúp nhìn lại các dấu hiệu được hỏi trong giai đoạn gần đây, không khẳng định rằng bạn không có bất kỳ khó khăn cảm xúc nào khác.'
        WHEN instrument = 'GAD7' AND screening_level = 'MILD' THEN 'Trong 14 ngày qua, các câu trả lời GAD-7 của bạn cho thấy một số dấu hiệu như lo lắng, căng thẳng hoặc khó thư giãn ở mức nhẹ. Bạn có thể dùng kết quả này để nhận ra tình huống nào thường đi cùng cảm giác lo âu và theo dõi xem chúng có kéo dài hoặc ảnh hưởng đến sinh hoạt hằng ngày hay không.'
        WHEN instrument = 'GAD7' AND screening_level = 'MODERATE' THEN 'Trong 14 ngày qua, các câu trả lời GAD-7 của bạn cho thấy nhiều dấu hiệu như lo lắng, căng thẳng hoặc khó thư giãn ở mức trung bình. Những trải nghiệm này có thể đáng để bạn quan tâm hơn, nhất là khi chúng làm gián đoạn giấc ngủ, khả năng tập trung, công việc, học tập hoặc các mối quan hệ.'
        WHEN instrument = 'GAD7' AND screening_level = 'SEVERE' THEN 'Trong 14 ngày qua, các câu trả lời GAD-7 của bạn cho thấy nhiều dấu hiệu như lo lắng, căng thẳng hoặc khó thư giãn ở mức nặng. Kết quả cho thấy các khó khăn được hỏi đến xuất hiện với tần suất cao; bạn nên cân nhắc sớm trao đổi trực tiếp với một chuyên gia phù hợp để được đánh giá đầy đủ hơn.'
    END,
    limitation_text = 'Kết quả này chỉ dựa trên câu trả lời tự khai của bạn trong 14 ngày qua. Bài sàng lọc không xác định nguyên nhân, không bao quát toàn bộ hoàn cảnh của bạn và không phải là chẩn đoán y khoa. Nếu những điều bạn đang trải qua khiến bạn lo lắng hoặc ảnh hưởng đến cuộc sống hằng ngày, bạn có thể cân nhắc trao đổi với một chuyên gia phù hợp.'
WHERE policy_version = 'mb-support-routing-capstone-v1';

--rollback UPDATE screening_band_meaning SET content_version = 'mb-screening-meaning-vi-vn-v1', meaning_text = CASE WHEN instrument = 'PHQ9' THEN 'Câu trả lời PHQ-9 của bạn thuộc mức triệu chứng ' || CASE screening_level WHEN 'MINIMAL' THEN 'tối thiểu' WHEN 'MILD' THEN 'nhẹ' WHEN 'MODERATE' THEN 'trung bình' WHEN 'MODERATELY_SEVERE' THEN 'khá nặng' WHEN 'SEVERE' THEN 'nặng' END || ' trong 14 ngày qua.' ELSE 'Câu trả lời GAD-7 của bạn thuộc mức triệu chứng ' || CASE screening_level WHEN 'MINIMAL' THEN 'tối thiểu' WHEN 'MILD' THEN 'nhẹ' WHEN 'MODERATE' THEN 'trung bình' WHEN 'SEVERE' THEN 'nặng' END || ' trong 14 ngày qua.' END, limitation_text = 'Kết quả này chỉ phản ánh câu trả lời tự khai trong 14 ngày qua. Đây là sàng lọc triệu chứng, không phải chẩn đoán y khoa và không thể hiện mức độ bệnh lý tổng thể.' WHERE policy_version = 'mb-support-routing-capstone-v1';
