export const CONFIGURATION_TOKEN = Symbol("CONFIGURATION_TOKEN");
export const LOGGER_TOKEN = Symbol("LOGGER_TOKEN");
export const METRICS_TOKEN = Symbol("METRICS_TOKEN");
export const READINESS_PROBE_TOKEN = Symbol("READINESS_PROBE_TOKEN");
